### PR TITLE
(Fix #70) include default case in switch statement to throw IllegalStateException

### LINKED ISSUE #70: [Source Code]: Add default case to AudioEventListener state checking
### What's Up?

In `tech.fastj.systems.audio.AudioEventListener`, inside the `AudioEventProcessor` Map, the mappings for audio start/stop check the `PlaybackState` in order to process actions. However, the current switch statements do not cover all cases.

I suggest adding default cases to each of the switch statements that throw illegal state exceptions -- these errors should state that the audio state was unexpected and invalid.

### Code of Conduct

- [X] I agree to follow FastJ's Code of Conduct

### PR DESCRIPTION
**Pull request by SaadRehmanCS**
…eException
 

## Additions
* Added default case for switch statements in 2 places in AudioEventProcessor.

### CODE REVIEW

File: src/main/java/tech/fastj/systems/audio/AudioEventListener.java [hunk 1]
```diff
@@ -6,6 +6,8 @@
 import java.util.function.BiConsumer;
 import java.util.function.Consumer;
 
+import static tech.fastj.systems.audio.state.PlaybackState.Stopped;
```
Comment (lucasstarsz) [inline src/main/java/tech/fastj/systems/audio/AudioEventListener.java:9]: Is there any part of the code which requires this import? I might be missing it from my mobile, but just to be sure.

**Comment by SaadRehmanCS** [comment]
`case Paused: {
                        audioEventListener.audioResumeAction.accept(audioEvent);
                    }` 
* I was wondering if you might want to add a `break` statement here?
* I also wanted to know if you would like me to include try-catch statements in places where AudioEventProcessor has been called. 
* I accidentally included a static import in line 9, shall I get rid of it?

File: src/main/java/tech/fastj/systems/audio/AudioEventListener.java [hunk 2]
```diff
@@ -34,6 +36,9 @@
                         audioEventListener.audioStartAction.accept(audioEvent);
                         break;
                     }
+                    default: {
+                        throw new IllegalStateException("audio state was unexpected and invalid");
```
Comment (lucasstarsz) [inline src/main/java/tech/fastj/systems/audio/AudioEventListener.java:40]: For both this segment and the other segment, it would be a good idea to include the playback state that caused the exception.

**Review by lucasstarsz — CHANGES_REQUESTED** [review]
Welcome to the FastJ repo! Thank you for contributing -- we really appreciate it! ❤️ 

Please take some time to review the comments I made on your pull request.

File: src/main/java/tech/fastj/systems/audio/AudioEventListener.java (hunk 1 above)
Comment (SaadRehmanCS) [reply src/main/java/tech/fastj/systems/audio/AudioEventListener.java:9]: My editor doesn't seem too happy with `Stopped` and `Paused` as it can't find a path to them.

**Comment by lucasstarsz** [comment]
> `case Paused: { audioEventListener.audioResumeAction.accept(audioEvent); }`
> 
> I was wondering if you might want to add a `break` statement here?

Actually, I've been meaning to include a comment explaining the lack of a break! Good catch.
The audio event system includes audio events for when audio is paused, and when the audio's playing stream is stopped (either temporarily or permanently). As of right now, I've intentionally had both trigger because it made sense at the time -- when an audio stream stops, ot could be either paused or completely stopped. If it is paused, then an extra event should be created for that. Feel free to dispute this though -- I've been considering adding those break statements for a while.
 
> I also wanted to know if you would like me to include try-catch statements in places where AudioEventProcessor has been called.

No need -- the audio state system is already designed to work properly, and hasn't given me any issues just yet.
That being said, it's never a bad idea to cover your bases!

> I accidentally included a static import in line 9, shall I get rid of it?

I wish I had seen this before publishing my review. Yes, go ahead and remove it 👍🏾

File: src/main/java/tech/fastj/systems/audio/AudioEventListener.java (hunk 1 above)
Comment (lucasstarsz) [reply src/main/java/tech/fastj/systems/audio/AudioEventListener.java:9]: Interesting... I'll have a look into the source code right now.

Comment (lucasstarsz) [reply src/main/java/tech/fastj/systems/audio/AudioEventListener.java:9]: After a bit of inspection, I agree -- that's a very weird bit of code you've found! I think IntellIJ on my side sees no issues with it because it resolves the Paused and Stopped as possibilities from the `getPlaybackState()` method call. It doesn't make too much sense that an import isn't required, given how Java normally is, but it is what it is I suppose.
What editor are you using that's giving you this issue?

Comment (SaadRehmanCS) [reply src/main/java/tech/fastj/systems/audio/AudioEventListener.java:9]: Funny enough, I'm using IntelliJ too!

Comment (lucasstarsz) [reply src/main/java/tech/fastj/systems/audio/AudioEventListener.java:9]: The mysteries of technology 🤣 
Either way, go ahead and remove the import. Might be worth looking into that import issue some more, but for this repo everything is fine.

File: src/main/java/tech/fastj/systems/audio/AudioEventListener.java (hunk 2 above)
Comment (SaadRehmanCS) [reply src/main/java/tech/fastj/systems/audio/AudioEventListener.java:40]: Just to make sure, do you mean to include `audioEventListener.audio.getPreviousPlaybackState()` as a string in the exception call, and so on for the second segment?

Comment (lucasstarsz) [reply src/main/java/tech/fastj/systems/audio/AudioEventListener.java:40]: Yep, just as a string in the exception(s). You're also free to abstract that method call into a value -- either or is fine with me.

**Comment by lucasstarsz** [comment]
I forgot to add -- let me know when you're all done with commits so I can do a follow-up review.

**Comment by SaadRehmanCS** [comment]
You can go ahead and review it now.

File: src/main/java/tech/fastj/systems/audio/AudioEventListener.java [hunk 3]
```diff
@@ -23,33 +26,51 @@
...
             },
             LineEvent.Type.CLOSE, (audioEvent, audioEventListener) -> audioEventListener.audioCloseAction.accept(audioEvent)
     );
 
+    /**
+     * Throws IllegalStateException when PlaybackState passes through default cases in switch statements in
+     * AudioEventProcessor
+     * @param p the playback state
+     */
+    private static void exceptionOnPlaybackState(PlaybackState p) {
```
Comment (lucasstarsz) [inline src/main/java/tech/fastj/systems/audio/AudioEventListener.java:70]: I appreciate the effort (and the abstraction of the state variable -- nice), but I don't think there's much need for a specific method just to throw that specific exception. It's a nice idea, but then that leads to having a whole bunch of abstractions all over the library with the same concept. 
That, and it clutters the stack trace if the error is actually thrown! There doesn't really need to be a layer of abstraction just for exception throwing, on top of what's already there.

**Review by lucasstarsz — CHANGES_REQUESTED** [review]
Just one more thing to clear up!

File: src/main/java/tech/fastj/systems/audio/AudioEventListener.java (hunk 3 above)
Comment (SaadRehmanCS) [reply src/main/java/tech/fastj/systems/audio/AudioEventListener.java:70]: Hmm that's true. I'll get rid of it!

**Review by lucasstarsz — APPROVED** [review]
Looks good to me 👍🏾

**Comment by lucasstarsz** [comment]
Thanks for contributing to FastJ! Hope to see you again sometime 👍🏾

**Comment by SaadRehmanCS** [comment]
Thank you!
